package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private String articuloClave;
     private int idarticulo;
     private String nombre;
     private Integer precio;
     private String descripcion;
     private String estatus;
     private Integer disponible;
     private Set paqueteDetalles = new HashSet(0);
     private Set facturaDetalles = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }
    public Articulo(int idarticulo, String nombre, Integer precio, String descripcion, String estatus, Integer disponible, Set paqueteDetalles, Set facturaDetalles) {
       this.idarticulo = idarticulo;
       this.nombre = nombre;
       this.precio = precio;
       this.descripcion = descripcion;
       this.estatus = estatus;
       this.disponible = disponible;
       this.paqueteDetalles = paqueteDetalles;
       this.facturaDetalles = facturaDetalles;
    }
   
    public String getArticuloClave() {
        return this.articuloClave;
    }
    
    public void setArticuloClave(String articuloClave) {
        this.articuloClave = articuloClave;
    }
    public int getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(int idarticulo) {
        this.idarticulo = idarticulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Integer getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(Integer disponible) {
        this.disponible = disponible;
    }
    public Set getPaqueteDetalles() {
        return this.paqueteDetalles;
    }
    
    public void setPaqueteDetalles(Set paqueteDetalles) {
        this.paqueteDetalles = paqueteDetalles;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }




}


