package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String nombre;
     private String apePat;
     private String apeMat;
     private String email;
     private String facebook;
     private String twitter;
     private String instagram;
     private String telCellular;
     private String telCasa;
     private String telTrabajo;
     private String estatus;
     private Set eventos = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String nombre, String apePat, String apeMat, String email, String facebook, String twitter, String instagram, String telCellular, String telCasa, String telTrabajo, String estatus, Set eventos, Set pagos) {
       this.nombre = nombre;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.email = email;
       this.facebook = facebook;
       this.twitter = twitter;
       this.instagram = instagram;
       this.telCellular = telCellular;
       this.telCasa = telCasa;
       this.telTrabajo = telTrabajo;
       this.estatus = estatus;
       this.eventos = eventos;
       this.pagos = pagos;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getInstagram() {
        return this.instagram;
    }
    
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }
    public String getTelCellular() {
        return this.telCellular;
    }
    
    public void setTelCellular(String telCellular) {
        this.telCellular = telCellular;
    }
    public String getTelCasa() {
        return this.telCasa;
    }
    
    public void setTelCasa(String telCasa) {
        this.telCasa = telCasa;
    }
    public String getTelTrabajo() {
        return this.telTrabajo;
    }
    
    public void setTelTrabajo(String telTrabajo) {
        this.telTrabajo = telTrabajo;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


