package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1



/**
 * EventoId generated by hbm2java
 */
public class EventoId  implements java.io.Serializable {


     private String salonClaveRef;
     private String eventoFecha;
     private String eventoHora;
     private String salonSalonClave;
     private String usuarioUsername;
     private int clienteIdcliente;

    public EventoId() {
    }

    public EventoId(String salonClaveRef, String eventoFecha, String eventoHora, String salonSalonClave, String usuarioUsername, int clienteIdcliente) {
       this.salonClaveRef = salonClaveRef;
       this.eventoFecha = eventoFecha;
       this.eventoHora = eventoHora;
       this.salonSalonClave = salonSalonClave;
       this.usuarioUsername = usuarioUsername;
       this.clienteIdcliente = clienteIdcliente;
    }
   
    public String getSalonClaveRef() {
        return this.salonClaveRef;
    }
    
    public void setSalonClaveRef(String salonClaveRef) {
        this.salonClaveRef = salonClaveRef;
    }
    public String getEventoFecha() {
        return this.eventoFecha;
    }
    
    public void setEventoFecha(String eventoFecha) {
        this.eventoFecha = eventoFecha;
    }
    public String getEventoHora() {
        return this.eventoHora;
    }
    
    public void setEventoHora(String eventoHora) {
        this.eventoHora = eventoHora;
    }
    public String getSalonSalonClave() {
        return this.salonSalonClave;
    }
    
    public void setSalonSalonClave(String salonSalonClave) {
        this.salonSalonClave = salonSalonClave;
    }
    public String getUsuarioUsername() {
        return this.usuarioUsername;
    }
    
    public void setUsuarioUsername(String usuarioUsername) {
        this.usuarioUsername = usuarioUsername;
    }
    public int getClienteIdcliente() {
        return this.clienteIdcliente;
    }
    
    public void setClienteIdcliente(int clienteIdcliente) {
        this.clienteIdcliente = clienteIdcliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventoId) ) return false;
		 EventoId castOther = ( EventoId ) other; 
         
		 return ( (this.getSalonClaveRef()==castOther.getSalonClaveRef()) || ( this.getSalonClaveRef()!=null && castOther.getSalonClaveRef()!=null && this.getSalonClaveRef().equals(castOther.getSalonClaveRef()) ) )
 && ( (this.getEventoFecha()==castOther.getEventoFecha()) || ( this.getEventoFecha()!=null && castOther.getEventoFecha()!=null && this.getEventoFecha().equals(castOther.getEventoFecha()) ) )
 && ( (this.getEventoHora()==castOther.getEventoHora()) || ( this.getEventoHora()!=null && castOther.getEventoHora()!=null && this.getEventoHora().equals(castOther.getEventoHora()) ) )
 && ( (this.getSalonSalonClave()==castOther.getSalonSalonClave()) || ( this.getSalonSalonClave()!=null && castOther.getSalonSalonClave()!=null && this.getSalonSalonClave().equals(castOther.getSalonSalonClave()) ) )
 && ( (this.getUsuarioUsername()==castOther.getUsuarioUsername()) || ( this.getUsuarioUsername()!=null && castOther.getUsuarioUsername()!=null && this.getUsuarioUsername().equals(castOther.getUsuarioUsername()) ) )
 && (this.getClienteIdcliente()==castOther.getClienteIdcliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSalonClaveRef() == null ? 0 : this.getSalonClaveRef().hashCode() );
         result = 37 * result + ( getEventoFecha() == null ? 0 : this.getEventoFecha().hashCode() );
         result = 37 * result + ( getEventoHora() == null ? 0 : this.getEventoHora().hashCode() );
         result = 37 * result + ( getSalonSalonClave() == null ? 0 : this.getSalonSalonClave().hashCode() );
         result = 37 * result + ( getUsuarioUsername() == null ? 0 : this.getUsuarioUsername().hashCode() );
         result = 37 * result + this.getClienteIdcliente();
         return result;
   }   


}


