package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private String facturaClave;
     private int idfactura;
     private String salonClave;
     private String clienteClave;
     private Integer total;
     private String fechaAlta;
     private String fechaModificacion;
     private String fechaCancelacion;
     private String estatus;
     private Set facturaDetalles = new HashSet(0);
     private Set pagos = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int idfactura) {
        this.idfactura = idfactura;
    }
    public Factura(int idfactura, String salonClave, String clienteClave, Integer total, String fechaAlta, String fechaModificacion, String fechaCancelacion, String estatus, Set facturaDetalles, Set pagos) {
       this.idfactura = idfactura;
       this.salonClave = salonClave;
       this.clienteClave = clienteClave;
       this.total = total;
       this.fechaAlta = fechaAlta;
       this.fechaModificacion = fechaModificacion;
       this.fechaCancelacion = fechaCancelacion;
       this.estatus = estatus;
       this.facturaDetalles = facturaDetalles;
       this.pagos = pagos;
    }
   
    public String getFacturaClave() {
        return this.facturaClave;
    }
    
    public void setFacturaClave(String facturaClave) {
        this.facturaClave = facturaClave;
    }
    public int getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(int idfactura) {
        this.idfactura = idfactura;
    }
    public String getSalonClave() {
        return this.salonClave;
    }
    
    public void setSalonClave(String salonClave) {
        this.salonClave = salonClave;
    }
    public String getClienteClave() {
        return this.clienteClave;
    }
    
    public void setClienteClave(String clienteClave) {
        this.clienteClave = clienteClave;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    public String getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(String fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(String fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getFechaCancelacion() {
        return this.fechaCancelacion;
    }
    
    public void setFechaCancelacion(String fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


