package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1



/**
 * PagoId generated by hbm2java
 */
public class PagoId  implements java.io.Serializable {


     private int idpago;
     private String facturaFacturaClave;
     private String usuarioUsername;
     private int clienteIdcliente;

    public PagoId() {
    }

    public PagoId(int idpago, String facturaFacturaClave, String usuarioUsername, int clienteIdcliente) {
       this.idpago = idpago;
       this.facturaFacturaClave = facturaFacturaClave;
       this.usuarioUsername = usuarioUsername;
       this.clienteIdcliente = clienteIdcliente;
    }
   
    public int getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(int idpago) {
        this.idpago = idpago;
    }
    public String getFacturaFacturaClave() {
        return this.facturaFacturaClave;
    }
    
    public void setFacturaFacturaClave(String facturaFacturaClave) {
        this.facturaFacturaClave = facturaFacturaClave;
    }
    public String getUsuarioUsername() {
        return this.usuarioUsername;
    }
    
    public void setUsuarioUsername(String usuarioUsername) {
        this.usuarioUsername = usuarioUsername;
    }
    public int getClienteIdcliente() {
        return this.clienteIdcliente;
    }
    
    public void setClienteIdcliente(int clienteIdcliente) {
        this.clienteIdcliente = clienteIdcliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagoId) ) return false;
		 PagoId castOther = ( PagoId ) other; 
         
		 return (this.getIdpago()==castOther.getIdpago())
 && ( (this.getFacturaFacturaClave()==castOther.getFacturaFacturaClave()) || ( this.getFacturaFacturaClave()!=null && castOther.getFacturaFacturaClave()!=null && this.getFacturaFacturaClave().equals(castOther.getFacturaFacturaClave()) ) )
 && ( (this.getUsuarioUsername()==castOther.getUsuarioUsername()) || ( this.getUsuarioUsername()!=null && castOther.getUsuarioUsername()!=null && this.getUsuarioUsername().equals(castOther.getUsuarioUsername()) ) )
 && (this.getClienteIdcliente()==castOther.getClienteIdcliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdpago();
         result = 37 * result + ( getFacturaFacturaClave() == null ? 0 : this.getFacturaFacturaClave().hashCode() );
         result = 37 * result + ( getUsuarioUsername() == null ? 0 : this.getUsuarioUsername().hashCode() );
         result = 37 * result + this.getClienteIdcliente();
         return result;
   }   


}


