package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1



/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private PagoId id;
     private Cliente cliente;
     private Factura factura;
     private Usuario usuario;
     private String facturaClaveRef;
     private String fechaPago;
     private Integer monto;
     private String estatus;
     private String usuarioClave;
     private Integer clienteClave;
     private String descripcion;

    public Pago() {
    }

	
    public Pago(PagoId id, Cliente cliente, Factura factura, Usuario usuario) {
        this.id = id;
        this.cliente = cliente;
        this.factura = factura;
        this.usuario = usuario;
    }
    public Pago(PagoId id, Cliente cliente, Factura factura, Usuario usuario, String facturaClaveRef, String fechaPago, Integer monto, String estatus, String usuarioClave, Integer clienteClave, String descripcion) {
       this.id = id;
       this.cliente = cliente;
       this.factura = factura;
       this.usuario = usuario;
       this.facturaClaveRef = facturaClaveRef;
       this.fechaPago = fechaPago;
       this.monto = monto;
       this.estatus = estatus;
       this.usuarioClave = usuarioClave;
       this.clienteClave = clienteClave;
       this.descripcion = descripcion;
    }
   
    public PagoId getId() {
        return this.id;
    }
    
    public void setId(PagoId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getFacturaClaveRef() {
        return this.facturaClaveRef;
    }
    
    public void setFacturaClaveRef(String facturaClaveRef) {
        this.facturaClaveRef = facturaClaveRef;
    }
    public String getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(String fechaPago) {
        this.fechaPago = fechaPago;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getUsuarioClave() {
        return this.usuarioClave;
    }
    
    public void setUsuarioClave(String usuarioClave) {
        this.usuarioClave = usuarioClave;
    }
    public Integer getClienteClave() {
        return this.clienteClave;
    }
    
    public void setClienteClave(Integer clienteClave) {
        this.clienteClave = clienteClave;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


