package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paquete generated by hbm2java
 */
public class Paquete  implements java.io.Serializable {


     private Integer idpaquete;
     private String nombre;
     private String descripcion;
     private Integer precio;
     private Date fecha;
     private String salonClaveRef;
     private String estatus;
     private Set paqueteDetalles = new HashSet(0);

    public Paquete() {
    }

    public Paquete(String nombre, String descripcion, Integer precio, Date fecha, String salonClaveRef, String estatus, Set paqueteDetalles) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fecha = fecha;
       this.salonClaveRef = salonClaveRef;
       this.estatus = estatus;
       this.paqueteDetalles = paqueteDetalles;
    }
   
    public Integer getIdpaquete() {
        return this.idpaquete;
    }
    
    public void setIdpaquete(Integer idpaquete) {
        this.idpaquete = idpaquete;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSalonClaveRef() {
        return this.salonClaveRef;
    }
    
    public void setSalonClaveRef(String salonClaveRef) {
        this.salonClaveRef = salonClaveRef;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public Set getPaqueteDetalles() {
        return this.paqueteDetalles;
    }
    
    public void setPaqueteDetalles(Set paqueteDetalles) {
        this.paqueteDetalles = paqueteDetalles;
    }




}


