package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1



/**
 * PaqueteDetalle generated by hbm2java
 */
public class PaqueteDetalle  implements java.io.Serializable {


     private PaqueteDetalleId id;
     private Articulo articulo;
     private Paquete paquete;
     private int idpaqueteDetalle;
     private Integer piezas;
     private Integer precio;
     private Integer descuento1;
     private String salonClaveRef;

    public PaqueteDetalle() {
    }

	
    public PaqueteDetalle(PaqueteDetalleId id, Articulo articulo, Paquete paquete, int idpaqueteDetalle) {
        this.id = id;
        this.articulo = articulo;
        this.paquete = paquete;
        this.idpaqueteDetalle = idpaqueteDetalle;
    }
    public PaqueteDetalle(PaqueteDetalleId id, Articulo articulo, Paquete paquete, int idpaqueteDetalle, Integer piezas, Integer precio, Integer descuento1, String salonClaveRef) {
       this.id = id;
       this.articulo = articulo;
       this.paquete = paquete;
       this.idpaqueteDetalle = idpaqueteDetalle;
       this.piezas = piezas;
       this.precio = precio;
       this.descuento1 = descuento1;
       this.salonClaveRef = salonClaveRef;
    }
   
    public PaqueteDetalleId getId() {
        return this.id;
    }
    
    public void setId(PaqueteDetalleId id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Paquete getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(Paquete paquete) {
        this.paquete = paquete;
    }
    public int getIdpaqueteDetalle() {
        return this.idpaqueteDetalle;
    }
    
    public void setIdpaqueteDetalle(int idpaqueteDetalle) {
        this.idpaqueteDetalle = idpaqueteDetalle;
    }
    public Integer getPiezas() {
        return this.piezas;
    }
    
    public void setPiezas(Integer piezas) {
        this.piezas = piezas;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Integer getDescuento1() {
        return this.descuento1;
    }
    
    public void setDescuento1(Integer descuento1) {
        this.descuento1 = descuento1;
    }
    public String getSalonClaveRef() {
        return this.salonClaveRef;
    }
    
    public void setSalonClaveRef(String salonClaveRef) {
        this.salonClaveRef = salonClaveRef;
    }




}


