package chania.model;
// Generated 27/11/2017 11:31:24 PM by Hibernate Tools 4.3.1



/**
 * PaqueteDetalleId generated by hbm2java
 */
public class PaqueteDetalleId  implements java.io.Serializable {


     private int idpaqueteReferencia;
     private String articuloClaveRef;

    public PaqueteDetalleId() {
    }

    public PaqueteDetalleId(int idpaqueteReferencia, String articuloClaveRef) {
       this.idpaqueteReferencia = idpaqueteReferencia;
       this.articuloClaveRef = articuloClaveRef;
    }
   
    public int getIdpaqueteReferencia() {
        return this.idpaqueteReferencia;
    }
    
    public void setIdpaqueteReferencia(int idpaqueteReferencia) {
        this.idpaqueteReferencia = idpaqueteReferencia;
    }
    public String getArticuloClaveRef() {
        return this.articuloClaveRef;
    }
    
    public void setArticuloClaveRef(String articuloClaveRef) {
        this.articuloClaveRef = articuloClaveRef;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaqueteDetalleId) ) return false;
		 PaqueteDetalleId castOther = ( PaqueteDetalleId ) other; 
         
		 return (this.getIdpaqueteReferencia()==castOther.getIdpaqueteReferencia())
 && ( (this.getArticuloClaveRef()==castOther.getArticuloClaveRef()) || ( this.getArticuloClaveRef()!=null && castOther.getArticuloClaveRef()!=null && this.getArticuloClaveRef().equals(castOther.getArticuloClaveRef()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdpaqueteReferencia();
         result = 37 * result + ( getArticuloClaveRef() == null ? 0 : this.getArticuloClaveRef().hashCode() );
         return result;
   }   


}


